[package]
name = "weirdboi_posthog"
version = "0.1.0"
edition = "2021"
authors = [
    "Louis Capitanchik <louis@weirdboi.com>"
]
license = "Apache-2.0"
description = "PostHog analytics integration for Bevy"
repository = "https://github.com/Commander-lol/weirdboi_posthog.git"
homepage = "https://github.com/Commander-lol/weirdboi_posthog"

[dependencies]
ehttp = { version = "0.5", features = ["native-async"] }
url = "2.5"
fastrand = "2"
serde_json = "1"
log = "0.4"
thiserror = "2"

bevy_ecs = { version = "0.17", features = ["backtrace"] }
bevy_time = "0.17"
bevy_tasks = "0.17"
bevy_app = "0.17"